spring:
  profiles:
    active: dev
    group:
      dev: dev
      dev-mocks: dev, mocks
  application.name: mugloar

wiremock.port: 8081

game.server:
  base-url: https://dragonsofmugloar.com/api/v2
  game-start-url: /game/start
  investigate-reputation-url: /:gameId/investigate/reputation
  messages-url: /:gameId/messages
  solve-url: /:gameId/solve/:adId
  shop-url: /:gameId/shop
  shop-buy-url: /:gameId/shop/buy/:itemId

game.mode: naive

training:
  number-of-parallel-games: 150
  training-rounds: 10
  games-in-one-round: 5
  player-count: 30
  number-of-survivors: 10
  mutation-chance-percentage: 0.1